modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="sshcracksadditions" #mandatory
version="${file.jarVersion}" #mandatory
displayName="sshcracks project additions mod" #mandatory
displayURL="https://github.com/sshcrack/custom_mod_project/" #optional
credits="Thanks to justcry_lp" #optional
authors="sshcrack" #optional
description='''
This is just a mod created by sshcrack specifically for this roleplay project you are playing. Enjoy!
'''

[[dependencies.sshcracksadditions]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"

    side="BOTH"
# Here's another dependency
[[dependencies.sshcracksadditions]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
